global using System.Buffers.Binary;
global using System.Collections.Concurrent;
global using System.Net;
global using System.Net.Sockets;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
